/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javadesk_500loc;

import Utils.DBCore;
import java.sql.SQLException;
import java.util.Vector;

/**
 *
 * @author son
 */
public class Productmanagement extends javax.swing.JPanel {

    /**
     * Creates new form Productmanagement
     */
    public Productmanagement() throws SQLException {
        initComponents();
        Vector temp = DBCore.testGetProduct("Mango");
        for (int i = 0; i < temp.size(); i++) {
            System.out.println(temp.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnChangeToBill = new javax.swing.JButton();

        btnChangeToBill.setText("Change to bill");
        btnChangeToBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeToBillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(btnChangeToBill, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(btnChangeToBill, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeToBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeToBillActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnChangeToBillActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeToBill;
    // End of variables declaration//GEN-END:variables
}
